name: Publish to PyPI
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    uses: bakdata/ci-templates/.github/workflows/python-poetry-publish-pypi.yaml@1.45.2
    with:
      publish-to-test: false
      poetry-version: "1.8.1"
    secrets:
      pypi-token: "${{ secrets.PYPI_TOKEN }}"
